### ISSUE TITLE
Yaml file understanding

### ISSUE THREAD

**Issue by thuiban** [asgeirrr/pgantomizer#2]
Hey ! I would like help for understand format file and where i put the table name. Can you help me ? Thank's

**Comment by thuiban** [comment]
Hi ! If i understand, in example_schema: `customer` and `customer_address` are table name. And raw is name of one column name ?

**Comment by asgeirrr** [comment]
All columns of the specified tables are dumped and anonymized by default. If you want to just copy some of the columns without anonymization, you must explicitly list them in the `raw` property (that's why it's called raw). Please refer to the README for details about the anonymization process.
