### ISSUE TITLE
Can't truncate tables with foreign keys

### ISSUE THREAD

**Issue by nbrustein** [asgeirrr/pgantomizer#8]
I have two tables that have a foreign key, and I want to truncate both of them. When I do it, though, I get the following error. 

```
psycopg2.errors.FeatureNotSupported: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "tutor_bot_messages" references "tutor_bot_conversations".
HINT:  Truncate table "tutor_bot_messages" at the same time, or use TRUNCATE ... CASCADE.
```

I asked ChatGPT for an answer:

 * how do i truncate tables with foreign keys using pgantomizer?
 * To truncate tables with foreign keys using pgantomizer, you can use the cascade_truncate function provided by the tool. The cascade_truncate function will automatically disable or drop the foreign key constraints, truncate the table, and then re-enable or recreate the foreign key constraints.

It would be great if that were actually true

**Comment by rlineweaver** [comment]
this functionality is now available in https://github.com/booleanbetrayal/pgantomizer/tree/misc-customizations

**Comment by booleanbetrayal** [comment]
Looks like this is also now in `master` and can be closed
